trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'c63dff65-153d-4bc6-8f65-55cf498bf638'
  imageRepository: 'shiveshcfootballmanager'
  containerRegistry: 'fmregistry123.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'
  aksServiceConnection: 'aks-connection'  # Azure RM service connection
  resourceGroup: 'Football-Manager'
  aksClusterName: 'fm-cluster'
  namespace: 'default'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: DeployToAKS
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: Default
    steps:
    - task: AzureCLI@2
      displayName: Deploy frontend to AKS
      inputs:
        azureSubscription: $(aksServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          # Get AKS credentials
          az aks get-credentials --resource-group $(resourceGroup) --name $(aksClusterName) --overwrite-existing
          
          # Replace image tag dynamically in deployment YAML
          (Get-Content "$(Build.SourcesDirectory)\frontend-deployment-az.yaml") -replace 'fmregistry123.azurecr.io/shiveshcfootballmanager:latest', "fmregistry123.azurecr.io/shiveshcfootballmanager:$(tag)" | Set-Content "$(Build.SourcesDirectory)\frontend-deployment-az.yaml"
          
          # Apply deployment and service
          kubectl apply -f "$(Build.SourcesDirectory)\frontend-deployment-az.yaml"
          kubectl apply -f "$(Build.SourcesDirectory)\frontend-service.yaml"
